### ISSUE TITLE
Add last updated date field

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#448] opened 2023-01-09 17:17 UTC
Additional column for last updated date and resize columns to accommodate extra field without looking cluttered.

**Comment by dcuellar322** [comment] 2023-04-17 00:58
![image.png](https://images.zenhubusercontent.com/64271dd2c2d1e674ff404655/5ae3fb02-0aa4-49ab-ad7b-19a27e7715e2)
This should be done.

**Comment by dspruell-i01** [comment] 2023-06-12 17:39
@dcuellar322 We believe this one's done, and it's probably a dupe of #431. I'll close this one out here and we'll post a verification out to Pedram on #431 to see if there's still anything outstanding.

**Closed by dspruell-i01** 2023-06-12 17:39 UTC
Labels: enhancement, threat-intel
