### ISSUE TITLE
Automated signature SC_Email_Body_with_Known_Phishing_URL takes a long time to load

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#434] opened 2022-08-22 16:59 UTC
Viewing, editing or pushing the status to Released take a very long time to complete. Much longer than the size would suggest. Occasionally timing out and returning an nginx error. (Will update when/if it is seen again)

**Comment by dcuellar322** [comment] 2023-04-17 01:04
This issue is a duplicate of #445, suggest we close one.

Could I get some clarity on if this is still an issue? After I moved the revisions to a separate modal?

**Comment by dspruell-i01** [comment] 2023-06-26 16:27
Closing out as dupe.

**Closed by dspruell-i01** 2023-06-26 16:27 UTC
