### ISSUE TITLE
Make the columns manually resizable.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#216] opened 2018-03-11 19:03 UTC

**Comment by ofzza** [comment] 2018-06-20 12:55
@pedramamini @danny248 
Seems like a duplicate of #224? Handling under the other issue (#224) ...

**Comment by ofzza** [comment] 2018-10-15 15:34
@pedramamini 
Closing this as it is a duplicate of now merged #224 (related also to #223)

**Closed by ofzza** 2018-10-15 15:34 UTC
