### ISSUE TITLE
Allow ui-grid column resize dynamically

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#224] opened 2018-06-19 16:49 UTC
**Branch**: `issue/224-table-column-widths` (PR #226)

**Comment by ofzza** [comment] 2018-06-20 12:55
@pedramamini @danny248 
Seems like a duplicate of #216?

Anyway, this is probably doable - need to dig into the 3rd party `ui-grid` control to make sure - but it will be a non-trivial amount of work.
I'll have a better look once the current `inquest-ui` milestone is out the door, providing the next milestone isn't too ambitious ...

**Comment by ofzza** [comment] 2018-07-08 21:35
@danny248 @pedramamini 

As instructed by @pedramamini, I've given up from making columns resizable for now and just set some default sizes and text-alignment that should make content more readable:

![image](https://user-images.githubusercontent.com/4250750/42424107-558a4e5e-8306-11e8-87fb-fc74efadc957.png)
![image](https://user-images.githubusercontent.com/4250750/42424117-848b316e-8306-11e8-9072-bebe4fe55c36.png)
![image](https://user-images.githubusercontent.com/4250750/42424133-fd2081ce-8306-11e8-86a2-03c3f579fa0d.png)

... especially in conjunction with #233:

![image](https://user-images.githubusercontent.com/4250750/42424152-6e3a86de-8307-11e8-9ca4-270091e3371c.png)
![image](https://user-images.githubusercontent.com/4250750/42424154-788ed4c8-8307-11e8-879a-69e38381ae59.png)
![image](https://user-images.githubusercontent.com/4250750/42424155-82c9b3ea-8307-11e8-8d75-0be91249b5e1.png)

**Comment by pedramamini** [comment] 2018-10-15 15:08
Merged.

**Closed by pedramamini** 2018-10-15 15:08 UTC
